services:
  backend:
    restart: always
    pull_policy: always
    env_file:
      - .env
    ports:
      - "4444:4444"
    image: mostafaewida/hackmaze_backend_spring:latest
    depends_on:
      - db

  frontend:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./config.js:/usr/share/nginx/html/config.js

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata

volumes:
  db_data: {}
