version: "3.8"

services:
  backend:
    restart: always
    env_file:
      - .env
    ports:
      - "8000:80"
    image: mostafaewida/hackmaze_backend:latest
    depends_on:
      - db

  frontend:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./config.js:/usr/share/nginx/html/config.js

  db:
    image: postgres:12
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata

volumes:
  db_data: {}

